# -*- coding: utf-8 -*-
"""Day_10_Defusin_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19GTF5WOtl2yraAU4sDmt9WAmjNjqAR1i
"""

# Mathematical models related to diffusion
# First we will take an image from Dataset
# Observe the noising step (beta which decides the rate of noising) of this image
# Denoise the same image (train our model)
# Trained model to decipher a sanskrit manuscript (diffusers library)

# Mathematical models related to diffusion

# Forward diffusion equation
# x(t) = (sqrt)(1-beta)x(t-1) + sqrt(beta*epsilon)

# x(t) = Noisy image
# epsilon = Gaussian noise
# beta = noise schedule

import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

transform = transforms.Compose([
    transforms.ToTensor()
])

dataset = torchvision.datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

# Select a fixed image

image_index = 0
x0, label = dataset[image_index]

print("Class label:", dataset.classes[label])

def add_noise(x, beta):
  noise = torch.randn_like(x)
  return torch.sqrt(1-beta)*x + torch.sqrt(beta)*noise

# Reverse Process

#Instead of directly predicting original image, it predicts
# epsilon(xt, t)

# Why?
# Predicting noise is easier than predicting image

# U-net backbone
# Time embedding
# Noise Scheduler

betas = [0.01, 0.05, 0.1, 0.3, 0.6]

for i,b in enumerate(betas):
  xt = add_noise(x0, torch.tensor(b))
  plt.subplot(1, len(betas)+1, i+2)
  plt.imshow(xt.permute(1,2,0).clamp(0,1))
  plt.title(f"beta={b}")
  plt.axis("off")

plt.show()

# More beta (noise scheduling parameter) => more destruction

plt.figure(figsize=(15,3))

plt.subplot(1, len(betas)+1, 1)
plt.imshow(x0.permute(1,2,0))

# Apply pretrained diffusion model

from diffusers import StableDiffusionPipeline
import torch
print("Is available :: ",torch.cuda.is_available())
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

prompt = "English alphabet"
image = pipe(prompt).images[0]
plt.imshow(image)
plt.axis("off")
plt.show()
image.save("output.png")

from PIL import Image

img = Image.open("output.png")
img.show()

# Image-to-Image Generation


from diffusers import StableDiffusionPipeline
import torch
print("Is available :: ",torch.cuda.is_available())
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

init_image = Image.open("edited.png")

prompt = "Can you increase the resolution, sharpen facial features"
image = pipe(prompt=prompt, image=init_image, strength=0.7).images[0]
plt.imshow(image)
plt.axis("off")
plt.show()
image.save("edited_2.png")

# Strength parameter controls how much noise is added
# More noise  ====> more creativity
# Less noise ===> More structure preservation

from PIL import Image

img = Image.open("output.png")
img.show()

#Extension Tasks for diffusion_Model
import torch
import torchvision
import torchvision.transforms as transforms

# Define a linear noise schedule
T = 1000 # Total timesteps
betas = torch.linspace(0.0001, 0.02, T)

# Precompute alphas and other terms
alphas = 1.0 - betas
alpha_bars = torch.cumprod(alphas, dim=0)

# Function to add noise at any timestep t
def q_sample(x_0, t, alpha_bars):
    noise = torch.randn_like(x_0)
    sqrt_alpha_bar = torch.sqrt(alpha_bars[t])
    sqrt_one_minus_alpha_bar = torch.sqrt(1.0 - alpha_bars[t])
    return sqrt_alpha_bar * x_0 + sqrt_one_minus_alpha_bar * noise, noise

# Re-define dataset for this cell to ensure x0 can be accessed
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = torchvision.datasets.CIFAR10(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

# Select the original image (x0) from earlier cells
image_index = 0 # Ensure image_index is defined
x0, _ = dataset[image_index] # Re-initialize x0 within this cell

# Visualize the forward diffusion process at various timesteps
num_steps_to_show = 8
steps = torch.linspace(0, T - 1, num_steps_to_show).long()

plt.figure(figsize=(20, 3))
plt.suptitle(f"Forward Diffusion Process: {num_steps_to_show} Timesteps")

for i, t in enumerate(steps):
    xt, _ = q_sample(x0, t, alpha_bars)
    plt.subplot(1, num_steps_to_show, i + 1)
    plt.imshow(xt.permute(1, 2, 0).clamp(0, 1))
    plt.title(f"t={t.item()}")
    plt.axis("off")

plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to make space for suptitle
plt.show()