# -*- coding: utf-8 -*-
"""Multi_Agent_observability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IdXdzHiOdR1ot4BiGRFEHeo3RT3AJLFG

## The task is to make the multi-agent workflow observable by adding:

- Structured JSON events
- Trace ID + Span ID
- Agent start/end logs
- Pipeline progress logs
- Failure location reporting
- Summary report

Below is a completed version using only Python standard libraries (no external dependency).
"""

import random
import time
import json
import uuid
from datetime import datetime


# ----------------------------
# Observability Logger
# ----------------------------

class ObservabilityLogger:

    def __init__(self):
        self.events = []
        self.trace_id = str(uuid.uuid4())


    def log_event(self, agent, event_type, details):

        event = {
            "timestamp": datetime.utcnow().isoformat(),
            "trace_id": self.trace_id,
            "span_id": str(uuid.uuid4()),
            "agent": agent,
            "event_type": event_type,
            "details": details
        }

        self.events.append(event)

        print(json.dumps(event, indent=2))


    def save(self):

        with open("trace.json", "w") as f:
            json.dump(
                self.events,
                f,
                indent=4
            )



# ----------------------------
# Agent Class
# ----------------------------

class Agent:

    def __init__(self, name, steps, logger):

        self.name = name
        self.steps = steps
        self.logger = logger


    def run(self):

        self.logger.log_event(
            self.name,
            "agent_started",
            {
                "total_steps": self.steps
            }
        )


        completed = 0


        for i in range(1, self.steps + 1):

            self.logger.log_event(
                self.name,
                "step_started",
                {
                    "step": i
                }
            )


            time.sleep(
                random.uniform(0.5,1)
            )


            # simulate failure
            if random.random() < 0.2:


                self.logger.log_event(
                    self.name,
                    "error",
                    {
                        "failed_step": i,
                        "message": "Random failure occurred"
                    }
                )


                return False



            completed += 1


            self.logger.log_event(
                self.name,
                "step_completed",
                {
                    "step": i
                }
            )


        self.logger.log_event(
            self.name,
            "agent_completed",
            {
                "completed_steps": completed
            }
        )


        return True



# ----------------------------
# Listener / Progress Tracker
# ----------------------------

class ProgressListener:


    def __init__(self):

        self.progress = {}



    def update(self, agent, status):

        self.progress[agent] = status

        print(
            f"[PROGRESS] {agent} --> {status}"
        )



# ----------------------------
# Pipeline Runner
# ----------------------------

def run_pipeline(agents):


    logger = ObservabilityLogger()

    listener = ProgressListener()


    results = {}



    for agent in agents:


        listener.update(
            agent.name,
            "running"
        )


        success = agent.run()


        results[agent.name] = success


        if success:

            listener.update(
                agent.name,
                "completed"
            )

        else:

            listener.update(
                agent.name,
                "failed"
            )



    logger.save()



    return results, logger



# ----------------------------
# Failure Analysis Summary
# ----------------------------

def create_summary(results, logger):


    failures = []


    for event in logger.events:

        if event["event_type"] == "error":

            failures.append(
                {
                    "agent":event["agent"],
                    "step":
                    event["details"]["failed_step"]
                }
            )



    summary = {

        "total_agents":
            len(results),

        "successful_agents":
            sum(results.values()),

        "failed_agents":
            len(results)
            -
            sum(results.values()),

        "failure_points":
            failures

    }


    with open(
        "summary.json",
        "w"
    ) as f:

        json.dump(
            summary,
            f,
            indent=4
        )


    print("\nSUMMARY")
    print(json.dumps(summary,indent=4))



# ----------------------------
# Main
# ----------------------------

if __name__ == "__main__":


    logger = ObservabilityLogger()


    agents = [

        Agent(
            "Planner",
            3,
            logger
        ),

        Agent(
            "Researcher",
            4,
            logger
        ),

        Agent(
            "Writer",
            2,
            logger
        )

    ]


    results, logger = run_pipeline(
        agents
    )


    create_summary(
        results,
        logger
    )


    print("\nDone")

""""Trace ID tracks the complete lifecycle of a request, while Span ID tracks individual operations inside that request.

In a multi-agent system, every agent action gets a unique span ID, which helps identify exactly which step caused latency or failure."

Trace ID: abc123

        Span ID
           |
           |
           +---- span001
           |       Retriever
           |
           +---- span002
           |       LLM Generation
           |
           +---- span003
                   Response Formatting

#Simple real-world analogy to understand trace_id and unique_id

Imagine a hospital visit--

Hospital Visit ID = Trace ID

Doctor consultation ID = Span ID

Blood test ID = Span ID

X-ray ID = Span ID
"""

import networkx as nx
import matplotlib.pyplot as plt


def draw_agent_graph():

    G = nx.DiGraph()


    G.add_edges_from(
        [
            ("User","Planner"),
            ("Planner","Researcher"),
            ("Researcher","Writer")
        ]
    )


    nx.draw(
        G,
        with_labels=True,
        node_size=3000
    )


    plt.title(
        "Multi Agent Workflow"
    )

    plt.show()



draw_agent_graph()



import matplotlib.pyplot as plt



def latency_chart():

    agents=[
        "Planner",
        "Researcher",
        "Writer"
    ]


    latency=[
        2,
        8,
        1
    ]


    plt.bar(
        agents,
        latency
    )


    plt.xlabel(
        "Agents"
    )


    plt.ylabel(
        "Seconds"
    )


    plt.title(
        "Agent Latency"
    )


    plt.show()



latency_chart()

