# -*- coding: utf-8 -*-
"""Smart_FAQ_Bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FFMGHzkIbxLSHQP1MFiMcwT71E_EGQu
"""

+------------------+
| 10 FAQ Strings   |
+--------+---------+
         |
         v
+---------------------------+
| SentenceTransformer       |
| all-MiniLM-L6-v2          |
+-------------+-------------+
              |
              v
+---------------------------+
| FAISS Vector Store        |
+-------------+-------------+
              |
              v
        User Query
              |
              v
+---------------------------+
| Similarity Search         |
| Top-2 Relevant FAQs       |
+-------------+-------------+
              |
              v
+---------------------------+
| Prompt Construction       |
| Context + User Question   |
+-------------+-------------+
              |
              v
+---------------------------+
| Groq LLM (Llama3)         |
+-------------+-------------+
              |
              v
+---------------------------+
| Final Answer              |
+---------------------------+

# Required packages
!pip install langchain
!pip install langchain-community
!pip install langchain-huggingface
!pip install sentence-transformers
!pip install faiss-cpu
!pip install groq

from google.colab import userdata
Groq_key=userdata.get('groq_apikey')

import os
from groq import Groq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# ==========================
# 1. FAQ Knowledge Base
# ==========================

faqs = [
    "How can I reset my password? Click on 'Forgot Password' on the login page.",
    "How do I update my email address? Go to Profile Settings and update your email.",
    "What payment methods are accepted? We accept UPI, Debit Card, Credit Card and Net Banking.",
    "How can I cancel my subscription? Navigate to Billing Settings and select Cancel Subscription.",
    "Do you offer refunds? Yes, refunds are available within 7 days of purchase.",
    "How can I contact customer support? Email us at support@example.com.",
    "Can I change my username? Yes, from the Profile section.",
    "How do I enable two-factor authentication? Visit Security Settings and enable 2FA.",
    "Is my personal data secure? Yes, all user data is encrypted.",
    "How can I upgrade my plan? Visit Subscription Settings and choose a higher plan."
]

# ==========================
# 2. Embedding Model
# ==========================

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# ==========================
# 3. Create FAISS Index
# ==========================

vector_store = FAISS.from_texts(
    texts=faqs,
    embedding=embedding_model
)

# ==========================
# 4. Groq Client
# ==========================

client = Groq(
    api_key="Groq_key"
)

# ==========================
# 5. Chat Loop
# ==========================

print("\nSmart FAQ Bot Started")
print("Type 'exit' to quit\n")

while True:

    query = input("You: ")

    if query.lower() == "exit":
        print("Bot: Goodbye!")
        break

    # Retrieve Top-2 FAQs
    retrieved_docs = vector_store.similarity_search_with_score(
        query,
        k=2
    )

    context = "\n".join(
        [doc.page_content for doc, score in retrieved_docs]
    )

    prompt = f"""
You are a FAQ assistant.

Use ONLY the provided FAQ context to answer.

FAQ Context:
{context}

Question:
{query}

Give a short and accurate answer.
"""

    response = client.chat.completions.create(
        model="llama3-8b-8192",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    answer = response.choices[0].message.content

    print("\nBot:", answer)

    print("\nTop Retrieved FAQs:")

    for i, (doc, score) in enumerate(retrieved_docs, start=1):
        print(f"{i}. Score: {score:.4f}")
        print(f"   FAQ: {doc.page_content}")

    print("-" * 60)