# -*- coding: utf-8 -*-
"""Timeseries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMrqny0A2NdTNwZPREnhCiHzFV4t-0uc
"""

# Import required packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/sakshi_ppg_20260611T074737_len148s.csv')
df

df.shape

df.dtypes

df.info()

df.describe()

df['timestamp_ms'].mean()

"""Important plot for this dataset"""

plt.hist(df['timestamp_ms'].diff(), bins=30)
plt.xlabel('Interval (ms)')
plt.ylabel('Frequency')
plt.show()

"""Decomposition- Decomposition refers to breaking down in its sub component like trend , seasonality and pattern.

Decomposition should be performed on the measured variable (such as sales, temperature, stock price, or PPG signal values) rather than on the timestamp itself.
"""

# Decompose RED signal
result = seasonal_decompose(
    df["red"],
    model="additive",
    period=50      # ~50 samples/sec in your dataset
)

result.plot()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose

result = seasonal_decompose(
    df['ir_corrected'],
    model='additive',
    period=50      # roughly 1 second at 50Hz
)

result.plot()

"""Stationarity check-"""

from statsmodels.tsa.stattools import adfuller

result = adfuller(df['red_corrected'])

print("ADF Statistic:", result[0])
print("p-value:", result[1])

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

df = pd.read_csv("sakshi_ppg_20260611T074737_len148s.csv")

signal = df["red_corrected"]

fig, axes = plt.subplots(2, 1, figsize=(12,8))

plot_acf(signal,
         lags=100,
         ax=axes[0])

axes[0].set_title("ACF - red_corrected")

plot_pacf(signal,
          lags=100,
          ax=axes[1],
          method='ywm')

axes[1].set_title("PACF - red_corrected")

plt.tight_layout()
plt.show()

rolling_mean = df['red'].rolling(window=30).mean()
rolling_std = df['red'].rolling(window=30).std()

plt.figure(figsize=(12,5))
plt.plot(df['red'], label='Original')
plt.plot(rolling_mean, label='Rolling Mean')
plt.plot(rolling_std, label='Rolling Std')
plt.legend()
plt.show()

import os

os.makedirs("artifacts", exist_ok=True)

plt.savefig("artifacts/acf_pacf_red_corrected.png")

import os

print(os.getcwd())

