# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vipIuf9ankVOJnpifdlMqoKE_T2R9ceF

# Day 18 · Colab 2 — Multi-tool Agent Chaining + Redis Event Queue

**Agentic Systems Bootcamp**

Here the agent does real **orchestration**: it *chains* tools to place an order —
`check_inventory → create_order → send_confirmation` — mixing **synchronous** tools
(SQLite reads/writes) with an **asynchronous** one (enqueue an email job onto a Redis Stream,
handled later by a separate **worker** via a consumer group).

Runs entirely in Colab: `fakeredis` provides `XADD` / `XREADGROUP`, SQLite is built in.

> **Patterns (from the deck):** *routing* (pick the right tool), *prompt chaining* (feed one tool's
> output into the next), *parallel* reads, and the **sync-vs-async** boundary — slow side-effects go
> on a queue so the agent turn stays fast.

## Step 1 — Install & configure
"""

!pip install -q anthropic fakeredis 2>/dev/null
import os, getpass
if not os.environ.get('ANTHROPIC_API_KEY'):
    try:
        from google.colab import userdata
        os.environ['ANTHROPIC_API_KEY'] = userdata.get('ANTHROPIC_API_KEY')
    except Exception:
        pass
if not os.environ.get('ANTHROPIC_API_KEY'):
    os.environ['ANTHROPIC_API_KEY'] = getpass.getpass('ANTHROPIC_API_KEY (blank = offline mock): ')
LIVE = bool(os.environ.get('ANTHROPIC_API_KEY'))
MODEL = 'claude-sonnet-4-6'
print('LIVE mode' if LIVE else 'OFFLINE mock mode')

"""## Step 2 — SQLite orders + inventory database

Two tables: `inventory` (stock per SKU) and `orders` (what we create).
All access is through **parameterised** SQL — never string-formatted — and reads are row-limited.
"""

import sqlite3
db = sqlite3.connect(':memory:', check_same_thread=False)
db.execute('CREATE TABLE inventory (sku TEXT PRIMARY KEY, name TEXT, qty INTEGER, price REAL)')
db.execute('CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT, qty INTEGER, total REAL, status TEXT)')
db.executemany('INSERT INTO inventory VALUES (?,?,?,?)', [
    ('KB-01', 'Mechanical keyboard', 12, 129.0),
    ('HUB-2', 'USB-C hub',           0,  58.0),
    ('MON-4', '4K monitor',          5, 410.0),
])
db.commit()
print('inventory seeded')

"""## Step 3 — A Redis Stream as the email job queue

`send_confirmation` won't send email inline (slow, can fail). It **enqueues** a job with `XADD` and
returns a `job_id` immediately. A **worker** later reads with `XREADGROUP` (a consumer group gives us
at-least-once delivery + acks) and writes the result back to a `jobresult:<id>` key.
"""

import fakeredis, json, time, uuid
r = fakeredis.FakeStrictRedis()
STREAM = 'emails'
GROUP  = 'mailers'
try:
    r.xgroup_create(STREAM, GROUP, id='0', mkstream=True)
except Exception as e:
    print('group exists:', e)

def enqueue_email(to, subject, body):
    job_id = uuid.uuid4().hex[:8]
    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': subject, 'body': body})
    r.set(f'jobresult:{job_id}', 'queued')
    return job_id

print('queue ready; sample job id ->', enqueue_email('a@x.com', 'hi', 'test'))

"""## Step 4 — The worker (consumer group)

In production this is a separate process. Here we drain the stream on demand. Each message is
processed, the result stored, and the message **acked** with `XACK` so it isn't redelivered.
"""

import threading, time

def run_worker(max_msgs=10):
    processed = 0
    resp = r.xreadgroup(GROUP, 'worker-1', {STREAM: '>'}, count=max_msgs, block=0)
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            job_id = f['job_id']
            to = f['to']
            retries = int(f.get('retries', 0))

            # Simulate email sending failure for addresses containing 'fail'
            if 'fail' in to:
                print(f"[Worker] Simulating failure for job {job_id} (to: {to})")
                if retries < 2: # Max 2 retries
                    print(f"[Worker] Retrying job {job_id}. Retries: {retries+1}")
                    # Re-enqueue with incremented retry count
                    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': f['subject'], 'body': f['body'], 'retries': retries + 1})
                    r.set(f"jobresult:{job_id}", f"retrying {retries+1}")
                else:
                    print(f"[Worker] Moving job {job_id} to DLQ (max retries reached)")
                    r.xadd(DLQ_STREAM, {'job_id': job_id, 'to': to, 'subject': f['subject'], 'body': f['body'], 'status': 'failed'})
                    r.set(f"jobresult:{job_id}", 'failed_dlq')
            else:
                # In a real scenario, this would call a real email provider
                print(f"[Worker] Sending email for job {job_id} to {to}")
                r.set(f"jobresult:{job_id}", 'sent')

            r.xack(STREAM, GROUP, msg_id)
            processed += 1
    return processed

def inspect_dlq():
    dlq_messages = []
    # Note: Using XREAD here with a simple ID to read all available messages up to now
    # For a consumer group, you'd typically use XREADGROUP once to claim pending messages,
    # and then subsequent XREADGROUP calls to read new messages.
    resp = r.xread({DLQ_STREAM: '0-0'}, count=100, block=0)
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            dlq_messages.append({'msg_id': msg_id.decode(), **f})
    return dlq_messages

# Background worker loop
worker_running = True
def worker_loop():
    while worker_running:
        processed_msgs = run_worker()
        if processed_msgs > 0:
            print(f"[Background Worker] Processed {processed_msgs} message(s).")
        time.sleep(0.1) # Small delay to avoid busy-waiting

# Start the worker in a separate thread
worker_thread = threading.Thread(target=worker_loop, daemon=True)
worker_thread.start()

print('Background worker thread started.')
# Initial run to process any messages from previous executions/tests
# print('worker processed', run_worker(), 'job(s)') # No longer needed as thread handles it

"""## Step 5 — Tool functions (sync + async)

`check_inventory` and `create_order` are **synchronous** — they touch SQLite and return immediately.
`create_order` re-checks stock and decrements it in one transaction (guarding against overselling).
`send_confirmation` is **asynchronous** — it enqueues and returns a `job_id`. `check_job` polls a result.
"""

def check_inventory(sku: str):
    row = db.execute('SELECT sku,name,qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not row:
        return {'error': f'unknown sku {sku}'}
    return {'sku': row[0], 'name': row[1], 'qty': row[2], 'price': row[3]}

def create_order(sku: str, qty: int):
    cur = db.execute('SELECT qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not cur:
        return {'error': f'unknown sku {sku}'}
    have, price = cur
    if qty <= 0:
        return {'error': 'qty must be positive'}
    if have < qty:
        return {'error': f'insufficient stock: have {have}, need {qty}'}
    db.execute('UPDATE inventory SET qty=qty-? WHERE sku=?', (qty, sku))
    cur2 = db.execute('INSERT INTO orders (sku,qty,total,status) VALUES (?,?,?,?)',
                      (sku, qty, round(price*qty, 2), 'created'))
    db.commit()
    return {'order_id': cur2.lastrowid, 'sku': sku, 'qty': qty, 'total': round(price*qty, 2)}

def send_confirmation(to: str, order_id: int):
    job_id = enqueue_email(to, f'Order {order_id} confirmed', f'Your order {order_id} is on its way.')
    return {'job_id': job_id, 'status': 'queued'}

def check_job(job_id: str):
    v = r.get(f'jobresult:{job_id}')
    return {'job_id': job_id, 'status': v.decode() if v else 'unknown'}

"""## Step 6 — Tool schemas + dispatch"""

import time

TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':'Create an order for a SKU and quantity. Fails if stock is insufficient.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
  {'name':'inspect_dlq','description':'Inspect the dead-letter queue for failed email jobs.',
   'input_schema':{'type':'object','properties':{}}},
  {'name': 'verify_order','description': 'Verify the details and status of a created order.',
   'input_schema': {'type': 'object', 'properties': {'order_id': {'type': 'integer'}}, 'required': ['order_id']}},
  {'name': 'approve_order', 'description': 'Approve an order that requires human intervention before fulfillment.',
   'input_schema': {'type': 'object', 'properties': {'order_id': {'type': 'integer'}}, 'required': ['order_id']}}
]
DISPATCH = {'check_inventory':check_inventory,'create_order':create_order,
            'send_confirmation':send_confirmation,'check_job':check_job,
            'inspect_dlq':inspect_dlq, 'verify_order':verify_order, 'approve_order':approve_order}

trace_spans = []

def run_tool(name, args):
    start_time = time.perf_counter()
    fn = DISPATCH.get(name)
    if not fn:
        end_time = time.perf_counter()
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': False, 'error': f'unknown tool {name}'})
        return {'error': f'unknown tool {name}'}, True
    try:
        out = fn(**args)
        end_time = time.perf_counter()
        is_err = isinstance(out, dict) and 'error' in out
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': not is_err, 'result': out})
        return out, is_err
    except Exception as e:
        end_time = time.perf_counter()
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': False, 'error': repr(e)})
        return {'error': repr(e)}, True

def print_trace_table():
    global trace_spans
    if not trace_spans:
        print('No tool calls made in this turn.')
        return

    print('\n--- Tool Call Trace ---')
    print(f"| {'Tool':<20} | {'Args':<40} | {'MS':>8} | {'OK':<5} |")
    print(f"| {'-'*20} | {'-'*40} | {'-'*8} | {'-'*5} |")
    for span in trace_spans:
        tool_name = span['tool']
        args_str = str(span['args'])
        if len(args_str) > 40: args_str = args_str[:37] + '...'
        ms = f"{span['ms']:.2f}"
        ok = '✅' if span['ok'] else '❌'
        print(f"| {tool_name:<20} | {args_str:<40} | {ms:>8} | {ok:<5} |")
    print('-----------------------')
    trace_spans = [] # Clear traces after printing

print('tools ready')

"""## Step 7 — The orchestrating agent loop

Same `stop_reason` loop as Colab 1, but now the model **chains** several tools in one turn and we
drain the worker afterwards. The offline mock scripts the full chain so the notebook runs without a key.
"""

import json
SYSTEM = (
  'You are an ordering agent. To place an order: first check_inventory, then create_order. ' \
  'If an order needs approval, use the `approve_order` tool. Then, send_confirmation with the returned order_id. ' \
  'After these steps, **you must use the `verify_order` tool to confirm the order details and status** before reporting success. ' \
  'Report the order total, the order status, and the email job status. ' \
  'If stock is insufficient, say so and do not create the order.'
)

def agent(user_text, max_steps=8, verbose=True):
    global trace_spans
    trace_spans = [] # Clear traces at the start of each agent turn

    if not LIVE:
        if verbose: print('… (mock) chaining check_inventory → create_order → send_confirmation')
        inv,_ = run_tool('check_inventory', {'sku':'MON-4'})
        od,_  = run_tool('create_order', {'sku':'MON-4','qty':1})
        jb,_  = run_tool('send_confirmation', {'to':'asha@x.com','order_id':od['order_id']})
        st,_  = run_tool('check_job', {'job_id':jb['job_id']})
        print_trace_table() # Print trace for mock run
        return f"(mock) Order {od['order_id']} total ${od['total']}; email {st['status']}."

    from anthropic import Anthropic
    A = Anthropic()
    messages = [{'role':'user','content':user_text}]
    for _ in range(max_steps):
        resp = A.messages.create(model=MODEL, max_tokens=1024, system=SYSTEM, tools=TOOLS, messages=messages)
        if resp.stop_reason == 'tool_use':
            messages.append({'role':'assistant','content':[b.model_dump() for b in resp.content]})
            results = []
            for b in resp.content:
                if b.type == 'tool_use':
                    if verbose: print(f'  → {b.name}({b.input})')
                    out, is_err = run_tool(b.name, b.input)
                    results.append({'type':'tool_result','tool_use_id':b.id,
                                    'content':json.dumps(out),'is_error':is_err})
            messages.append({'role':'user','content':results})
            continue

        final_response = ''.join(b.text for b in resp.content if b.type=='text')
        print_trace_table() # Print trace for live run
        return final_response

    print_trace_table() # Print trace if max steps reached
    return '(max steps reached)'

print(agent('Order one 4K monitor (SKU MON-4) and email asha@x.com the confirmation.'))

"""## Step 8 — Show the resulting state"""

print('Orders table:')
for row in db.execute('SELECT id,sku,qty,total,status FROM orders').fetchall():
    print(' ', row)
print('Remaining stock:')
for row in db.execute('SELECT sku,qty FROM inventory').fetchall():
    print(' ', row)
# Try an out-of-stock order to see graceful failure
print('Out-of-stock attempt:', run_tool('create_order', {'sku':'HUB-2','qty':1}))

"""## Extension tasks

1. **Dead-letter & retry.** Make the worker fail jobs whose `to` is invalid; move them to an `emails:dlq`
   stream after N retries instead of acking. Add a tool to inspect the DLQ.
2. **Evaluator / verify step.** Add a `verify_order` tool that re-reads the order and confirms total &
   status; have the system prompt require it before declaring success (evaluator-optimiser pattern).
3. **Orchestrator-worker split.** Move `run_worker()` into a background `threading.Thread` loop so the
   agent never calls it directly; the queue truly decouples them.
4. **Human-in-the-loop gate.** For orders above a value threshold, have `create_order` return
   `{'status':'needs_approval'}` and require an `approve_order(order_id)` tool call before fulfilment.
5. **Trace spans.** Wrap `run_tool` to record `{tool, args, ms, ok}` per call; print a per-turn trace table.
6. **Prompt caching + token savings.** Mark the system prompt and tool block as cache-eligible and compare
   `usage.cache_read_input_tokens` across two identical turns; report the measured savings.

> **Stretch:** replace `fakeredis` with a real Redis (`redis.Redis.from_url(os.environ['REDIS_URL'])`) and
> run the worker as a genuinely separate Colab cell / process. The stream + consumer-group code is identical.
"""

def verify_order(order_id: int):
    row = db.execute('SELECT id, sku, qty, total, status FROM orders WHERE id=? LIMIT 1', (order_id,)).fetchone()
    if not row:
        return {'error': f'Order {order_id} not found'}

    order_details = {'id': row[0], 'sku': row[1], 'qty': row[2], 'total': row[3], 'status': row[4]}

    # In a real system, you might have a 'target_status' or 'expected_total'
    # For this example, we just confirm its existence and status.
    is_verified = order_details['status'] in ['created', 'sent'] # Assuming 'created' means it's in the DB, 'sent' means email confirmed

    return {'order_id': order_id, 'verified': is_verified, 'details': order_details}

"""### Integrating `verify_order` tool"""

TOOLS.append({
    'name': 'verify_order',
    'description': 'Verify the details and status of a created order.',
    'input_schema': {'type': 'object', 'properties': {'order_id': {'type': 'integer'}}, 'required': ['order_id']}
})

DISPATCH['verify_order'] = verify_order

print('verify_order tool added to TOOLS and DISPATCH.')

"""### Updating the agent's system prompt"""

SYSTEM = (
  'You are an ordering agent. To place an order: first check_inventory, then create_order, ' \
  'then send_confirmation with the returned order_id. After these steps, ' \
  '**you must use the `verify_order` tool to confirm the order details and status** before reporting success. ' \
  'Report the order total and the email job status. ' \
  'If stock is insufficient, say so and do not create the order.'
)

print('SYSTEM prompt updated.')

"""### Demonstration of the updated agent behavior"""

print(agent('Order two mechanical keyboards (SKU KB-01) and email test@x.com the confirmation.'))

"""### Demonstration of Background Worker and Dead-Letter Queue"""

# Send an email that will fail and go to DLQ
print("Attempting to send an email to 'fail_recipient@x.com' to demonstrate DLQ:")
dlq_job = send_confirmation('fail_recipient@x.com', 4) # Assuming order_id 4 for a new order
print(f"Initial status for DLQ job {dlq_job['job_id']}: {check_job(dlq_job['job_id'])['status']}")

# Give the background worker some time to process retries and move to DLQ
import time
print("Waiting for background worker to process... (3 seconds)")
time.sleep(3)

# Check the status of the job multiple times as the worker retries
print(f"Status after 1st retry: {check_job(dlq_job['job_id'])['status']}")
time.sleep(1)
print(f"Status after 2nd retry: {check_job(dlq_job['job_id'])['status']}")
time.sleep(1)
print(f"Final status (should be in DLQ): {check_job(dlq_job['job_id'])['status']}")

# Inspect the Dead-Letter Queue directly
print("\nInspecting Dead-Letter Queue:")
print(inspect_dlq())

"""## Step 9 — Extension: Human-in-the-loop gate (for high-value orders)

For orders above a certain value threshold, `create_order` will return a status of `needs_approval`. An `approve_order(order_id)` tool will then be required to fulfill it.
"""

APPROVAL_THRESHOLD = 500.0

def approve_order(order_id: int):
    # In a real system, this would involve a human approval process.
    # For this demo, we'll just mark it as 'approved'.
    row = db.execute('SELECT status FROM orders WHERE id=? LIMIT 1', (order_id,)).fetchone()
    if not row:
        return {'error': f'Order {order_id} not found'}
    if row[0] != 'needs_approval':
        return {'error': f'Order {order_id} does not need approval (current status: {row[0]})'}

    db.execute('UPDATE orders SET status=? WHERE id=?', ('created', order_id))
    db.commit()
    return {'order_id': order_id, 'status': 'approved'}

# Modify create_order to include approval logic
def create_order(sku: str, qty: int):
    cur = db.execute('SELECT qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not cur:
        return {'error': f'unknown sku {sku}'}
    have, price = cur
    if qty <= 0:
        return {'error': 'qty must be positive'}
    if have < qty:
        return {'error': f'insufficient stock: have {have}, need {qty}'}

    total = round(price * qty, 2)
    status = 'created'
    if total > APPROVAL_THRESHOLD:
        status = 'needs_approval'

    db.execute('UPDATE inventory SET qty=qty-? WHERE sku=?', (qty, sku))
    cur2 = db.execute('INSERT INTO orders (sku,qty,total,status) VALUES (?,?,?,?)',
                      (sku, qty, total, status))
    db.commit()
    return {'order_id': cur2.lastrowid, 'sku': sku, 'qty': qty, 'total': total, 'status': status}

print('Human-in-the-loop gate setup complete.')

"""### Integrating new tool and updating agent prompt"""

TOOLS.append({
    'name': 'approve_order',
    'description': 'Approve an order that requires human intervention before fulfillment.',
    'input_schema': {'type': 'object', 'properties': {'order_id': {'type': 'integer'}}, 'required': ['order_id']}
})

DISPATCH['approve_order'] = approve_order

SYSTEM = (
  'You are an ordering agent. To place an order: first check_inventory, then create_order. ' \
  'If an order needs approval, use the `approve_order` tool. Then, send_confirmation with the returned order_id. ' \
  'After these steps, **you must use the `verify_order` tool to confirm the order details and status** before reporting success. ' \
  'Report the order total, the order status, and the email job status. ' \
  'If stock is insufficient, say so and do not create the order.'
)

print('TOOLS, DISPATCH and SYSTEM prompt updated for human-in-the-loop.')

"""### Demonstration of Human-in-the-loop gate"""

# Order below threshold (should proceed normally)
print(agent('Order one USB-C hub (SKU HUB-2) and email user@example.com.')) # Note: HUB-2 has 0 stock, will demonstrate 'insufficient stock'
print("\n----------------------------------\n")
# Order above threshold (should trigger approval flow)
print(agent('Order three 4K monitors (SKU MON-4) and email manager@example.com.'))
print("\n----------------------------------\n")
# Re-check inventory for MON-4
print(check_inventory('MON-4'))

"""### Consolidating all definitions and re-running demonstrations"""

import sqlite3, fakeredis, json, time, uuid, threading, os, getpass
from anthropic import Anthropic

# --- Step 1: Install & configure (re-executed for completeness) ---
# !pip install -q anthropic fakeredis 2>/dev/null
# Already installed, so skipping pip install

if not os.environ.get('ANTHROPIC_API_KEY'):
    try:
        from google.colab import userdata
        os.environ['ANTHROPIC_API_KEY'] = userdata.get('ANTHROPIC_API_KEY')
    except Exception:
        pass
if not os.environ.get('ANTHROPIC_API_KEY'):
    os.environ['ANTHROPIC_API_KEY'] = getpass.getpass('ANTHROPIC_API_KEY (blank = offline mock): ')
LIVE = bool(os.environ.get('ANTHROPIC_API_KEY'))
MODEL = 'claude-sonnet-4-6'
print('LIVE mode' if LIVE else 'OFFLINE mock mode')

# --- Step 2: SQLite orders + inventory database (re-executed) ---
db = sqlite3.connect(':memory:', check_same_thread=False)
db.execute('CREATE TABLE inventory (sku TEXT PRIMARY KEY, name TEXT, qty INTEGER, price REAL)')
db.execute('CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT, qty INTEGER, total REAL, status TEXT)')
db.executemany('INSERT INTO inventory VALUES (?,?,?,?)', [
    ('KB-01', 'Mechanical keyboard', 12, 129.0),
    ('HUB-2', 'USB-C hub',           0,  58.0),
    ('MON-4', '4K monitor',          5, 410.0),
])
db.commit()
print('inventory seeded')

# --- Step 3: A Redis Stream as the email job queue (re-executed with DLQ additions) ---
r = fakeredis.FakeStrictRedis()
STREAM = 'emails'
GROUP  = 'mailers'
DLQ_STREAM = 'emails:dlq'
DLQ_GROUP = 'mailers_dlq'
# Consumer groups will be created after flushall for clean state

def enqueue_email(to, subject, body, retries=0):
    job_id = uuid.uuid4().hex[:8]
    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': subject, 'body': body, 'retries': retries})
    r.set(f'jobresult:{job_id}', 'queued')
    return job_id

print('queue ready; DLQ stream names defined.')

# --- Step 4: The worker (consumer group) (re-executed with DLQ and background thread) ---
worker_running = True

def run_worker(max_msgs=10):
    processed = 0
    # Use block=100 so it doesn't block indefinitely in the thread, but waits a bit for messages
    try:
        resp = r.xreadgroup(GROUP, 'worker-1', {STREAM: '>'}, count=max_msgs, block=100)
    except Exception as e:
        # This catch is mainly for the 'NOGROUP' error if group was somehow deleted or not created
        # print(f"[Worker Error] Failed to read from stream: {e}")
        return 0 # No messages processed if there's an error

    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            job_id = f['job_id']
            to = f['to']
            retries = int(f.get('retries', 0))

            if 'fail' in to:
                print(f"[Worker] Simulating failure for job {job_id} (to: {to})")
                if retries < 2:
                    print(f"[Worker] Retrying job {job_id}. Retries: {retries+1}")
                    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': f['subject'], 'body': f['body'], 'retries': retries + 1})
                    r.set(f"jobresult:{job_id}", f"retrying {retries+1}")
                else:
                    print(f"[Worker] Moving job {job_id} to DLQ (max retries reached)")
                    r.xadd(DLQ_STREAM, {'job_id': job_id, 'to': to, 'subject': f['subject'], 'body': f['body'], 'status': 'failed'})
                    r.set(f"jobresult:{job_id}", 'failed_dlq')
            else:
                print(f"[Worker] Sending email for job {job_id} to {to}")
                r.set(f"jobresult:{job_id}", 'sent')

            r.xack(STREAM, GROUP, msg_id)
            processed += 1
    return processed

def inspect_dlq():
    dlq_messages = []
    # Read all messages from DLQ_STREAM from the beginning, without acknowledging for inspection
    # Use block=0 to ensure it doesn't wait for new messages, just returns what's there
    resp = r.xread({DLQ_STREAM: '0-0'}, count=100, block=0)
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            dlq_messages.append({'msg_id': msg_id.decode(), **f})
    return dlq_messages

def worker_loop():
    while worker_running:
        processed_msgs = run_worker()
        if processed_msgs > 0:
            print(f"[Background Worker] Processed {processed_msgs} message(s).")
        # Small delay to avoid busy-waiting, worker will block for max 100ms anyway
        time.sleep(0.01)

# --- Step 5: Tool functions (sync + async) (consolidated and updated) ---
def check_inventory(sku: str):
    row = db.execute('SELECT sku,name,qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not row:
        return {'error': f'unknown sku {sku}'}
    return {'sku': row[0], 'name': row[1], 'qty': row[2], 'price': row[3]}

def send_confirmation(to: str, order_id: int):
    job_id = enqueue_email(to, f'Order {order_id} confirmed', f'Your order {order_id} is on its way.')
    return {'job_id': job_id, 'status': 'queued'}

def check_job(job_id: str):
    v = r.get(f'jobresult:{job_id}')
    return {'job_id': job_id, 'status': v.decode() if v else 'unknown'}

def verify_order(order_id: int):
    row = db.execute('SELECT id, sku, qty, total, status FROM orders WHERE id=? LIMIT 1', (order_id,)).fetchone()
    if not row:
        return {'error': f'Order {order_id} not found'}
    order_details = {'id': row[0], 'sku': row[1], 'qty': row[2], 'total': row[3], 'status': row[4]}
    is_verified = order_details['status'] in ['created', 'sent']
    return {'order_id': order_id, 'verified': is_verified, 'details': order_details}

APPROVAL_THRESHOLD = 500.0

def approve_order(order_id: int):
    row = db.execute('SELECT status FROM orders WHERE id=? LIMIT 1', (order_id,)).fetchone()
    if not row:
        return {'error': f'Order {order_id} not found'}
    if row[0] != 'needs_approval':
        return {'error': f'Order {order_id} does not need approval (current status: {row[0]})'}

    db.execute('UPDATE orders SET status=? WHERE id=?', ('created', order_id))
    db.commit()
    return {'order_id': order_id, 'status': 'approved'}

def create_order(sku: str, qty: int):
    cur = db.execute('SELECT qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not cur:
        return {'error': f'unknown sku {sku}'}
    have, price = cur
    if qty <= 0:
        return {'error': 'qty must be positive'}
    if have < qty:
        return {'error': f'insufficient stock: have {have}, need {qty}'}

    total = round(price * qty, 2)
    status = 'created'
    if total > APPROVAL_THRESHOLD:
        status = 'needs_approval'

    db.execute('UPDATE inventory SET qty=qty-? WHERE sku=?', (qty, sku))
    cur2 = db.execute('INSERT INTO orders (sku,qty,total,status) VALUES (?,?,?,?)',
                      (sku, qty, total, status))
    db.commit()
    return {'order_id': cur2.lastrowid, 'sku': sku, 'qty': qty, 'total': total, 'status': status}

print('All tool functions defined.')

# --- Step 6: Tool schemas + dispatch (consolidated and updated with tracing) ---
TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':'Create an order for a SKU and quantity. Fails if stock is insufficient.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
  {'name':'inspect_dlq','description':'Inspect the dead-letter queue for failed email jobs.',
   'input_schema':{'type':'object','properties':{}}},
  {'name': 'verify_order','description': 'Verify the details and status of a created order.',
   'input_schema': {'type': 'object', 'properties': {'order_id': {'type': 'integer'}}, 'required': ['order_id']}},
  {'name': 'approve_order', 'description': 'Approve an order that requires human intervention before fulfillment.',
   'input_schema': {'type': 'object', 'properties': {'order_id': {'type': 'integer'}}, 'required': ['order_id']}}
]
DISPATCH = {'check_inventory':check_inventory,'create_order':create_order,
            'send_confirmation':send_confirmation,'check_job':check_job,
            'inspect_dlq':inspect_dlq, 'verify_order':verify_order, 'approve_order':approve_order}

trace_spans = []

def run_tool(name, args):
    start_time = time.perf_counter()
    fn = DISPATCH.get(name)
    if not fn:
        end_time = time.perf_counter()
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': False, 'error': f'unknown tool {name}'})
        return {'error': f'unknown tool {name}'}, True
    try:
        out = fn(**args)
        end_time = time.perf_counter()
        is_err = isinstance(out, dict) and 'error' in out
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': not is_err, 'result': out})
        return out, is_err
    except Exception as e:
        end_time = time.perf_counter()
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': False, 'error': repr(e)})
        return {'error': repr(e)}, True

def print_trace_table():
    global trace_spans
    if not trace_spans:
        print('No tool calls made in this turn.')
        return

    print('\n--- Tool Call Trace ---')
    print(f"| {'Tool':<20} | {'Args':<40} | {'MS':>8} | {'OK':<5} |")
    print(f"| {'-'*20} | {'-'*40} | {'-'*8} | {'-'*5} |")
    for span in trace_spans:
        tool_name = span['tool']
        args_str = str(span['args'])
        if len(args_str) > 40: args_str = args_str[:37] + '...'
        ms = f"{span['ms']:.2f}"
        ok = '✅' if span['ok'] else '❌'
        print(f"| {tool_name:<20} | {args_str:<40} | {ms:>8} | {ok:<5} |")
    print('-----------------------')
    trace_spans = [] # Clear traces after printing

print('TOOLS, DISPATCH, run_tool, print_trace_table defined.')

# --- Step 7: The orchestrating agent loop (re-executed with updated SYSTEM and tracing) ---
SYSTEM = (
  'You are an ordering agent. To place an order: first check_inventory, then create_order. ' \
  'If an order needs approval, use the `approve_order` tool. Then, send_confirmation with the returned order_id. ' \
  'After these steps, **you must use the `verify_order` tool to confirm the order details and status** before reporting success. ' \
  'Report the order total, the order status, and the email job status. ' \
  'If stock is insufficient, say so and do not create the order.'
)

def agent(user_text, max_steps=8, verbose=True):
    global trace_spans
    trace_spans = [] # Clear traces at the start of each agent turn

    if not LIVE:
        if verbose: print('… (mock) chaining check_inventory → create_order → send_confirmation')
        inv,_ = run_tool('check_inventory', {'sku':'MON-4'})
        od,_  = run_tool('create_order', {'sku':'MON-4','qty':1})
        jb,_  = run_tool('send_confirmation', {'to':'asha@x.com','order_id':od['order_id']})
        st,_  = run_tool('check_job', {'job_id':jb['job_id']})
        print_trace_table() # Print trace for mock run
        return f"(mock) Order {od['order_id']} total ${od['total']}; email {st['status']}."

    A = Anthropic()
    messages = [{'role':'user','content':user_text}]
    for _ in range(max_steps):
        resp = A.messages.create(model=MODEL, max_tokens=1024, system=SYSTEM, tools=TOOLS, messages=messages)
        if resp.stop_reason == 'tool_use':
            messages.append({'role':'assistant','content':[b.model_dump() for b in resp.content]})
            results = []
            for b in resp.content:
                if b.type == 'tool_use':
                    if verbose: print(f'  → {b.name}({b.input})')
                    out, is_err = run_tool(b.name, b.input)
                    results.append({'type':'tool_result','tool_use_id':b.id,
                                    'content':json.dumps(out),'is_error':is_err})
            messages.append({'role':'user','content':results})
            continue

        final_response = ''.join(b.text for b in resp.content if b.type=='text')
        print_trace_table() # Print trace for live run
        return final_response

    print_trace_table() # Print trace if max steps reached
    return '(max steps reached)'

print('Agent function with tracing defined.')

# --- Resetting inventory and Redis for fresh demonstrations ---
print('\n--- Resetting inventory and Redis for fresh demonstrations ---\n')
db.execute('DROP TABLE IF EXISTS inventory')
db.execute('DROP TABLE IF EXISTS orders')
db.execute('CREATE TABLE inventory (sku TEXT PRIMARY KEY, name TEXT, qty INTEGER, price REAL)')
db.execute('CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT, qty INTEGER, total REAL, status TEXT)')
db.executemany('INSERT INTO inventory VALUES (?,?,?,?)', [
    ('KB-01', 'Mechanical keyboard', 12, 129.0),
    ('HUB-2', 'USB-C hub',           0,  58.0),
    ('MON-4', '4K monitor',          5, 410.0),
])
db.commit()
print('Inventory and orders tables reset.')

# Clear Redis for a clean demonstration
r.flushall()
# Explicitly recreate consumer groups after flushing Redis
try:
    r.xgroup_create(STREAM, GROUP, id='0', mkstream=True)
    r.xgroup_create(DLQ_STREAM, DLQ_GROUP, id='0', mkstream=True)
    print('Redis flushed and consumer groups recreated.')
except Exception as e:
    print(f'Error recreating Redis consumer groups: {e}. Attempting to proceed.')

# Ensure only one worker thread is started if this cell is re-executed
if not any(t.name == 'WorkerThread' for t in threading.enumerate()):
    worker_thread = threading.Thread(target=worker_loop, daemon=True, name='WorkerThread')
    worker_thread.start()
    print('Background worker thread started.')
else:
    print('Background worker thread already running.')

# --- Rerunning DLQ demonstration ---
print('\n--- Rerunning DLQ demonstration ---\n')
print("Attempting to send an email to 'fail_recipient@x.com' to demonstrate DLQ:")
dlq_job = send_confirmation('fail_recipient@x.com', 99) # Using a dummy order_id
print(f"Initial status for DLQ job {dlq_job['job_id']}: {check_job(dlq_job['job_id'])['status']}")

print("Waiting for background worker to process... (5 seconds)") # Extended sleep time
time.sleep(5)

print(f"Status after retries: {check_job(dlq_job['job_id'])['status']}")

print("\nInspecting Dead-Letter Queue:")
print(inspect_dlq())

# --- Rerunning Human-in-the-loop demonstration ---
print('\n--- Rerunning Human-in-the-loop demonstration ---\n')
# Order below threshold (should proceed normally) - HUB-2 has 0 stock initially
print(agent('Order one USB-C hub (SKU HUB-2) and email user@example.com.'))
print("\n----------------------------------\n")
# Order above threshold (should trigger approval flow) - MON-4 has 5 stock initially
print(agent('Order three 4K monitors (SKU MON-4) and email manager@example.com.'))
print("\n----------------------------------\n")
# Check state after the high-value order attempt
print('Remaining stock for MON-4 after agent attempt:')
print(check_inventory('MON-4'))

# Manually approve the pending order (simulate human intervention)
print('\n--- Manually approving the pending high-value order ---\n')
pending_order_id = db.execute("SELECT id FROM orders WHERE status='needs_approval' LIMIT 1").fetchone()
if pending_order_id:
    approved_result, _ = run_tool('approve_order', {'order_id': pending_order_id[0]})
    print(f"Approval result: {approved_result}")

    # Rerun agent to finalize the order after approval
    print('\n--- Re-running agent to finalize approved order ---\n')
    # Use a generic prompt that allows the agent to pick up the approval task and continue
    print(agent(f'Order {pending_order_id[0]} has been approved. Please finalize it and send confirmation to manager@example.com.'))
else:
    print('No order found requiring approval.')

print('\n--- Final Orders and Inventory State ---\n')
print('Orders table:')
for row in db.execute('SELECT id,sku,qty,total,status FROM orders').fetchall():
    print(' ', row)
print('Remaining stock:')
for row in db.execute('SELECT sku,qty FROM inventory').fetchall():
    print(' ', row)

"""### Re-initializing definitions and re-running demonstrations"""

# Re-execute dcoT_ZBCVR-h to ensure DLQ_STREAM and DLQ_GROUP are defined
import fakeredis, json, time, uuid
r = fakeredis.FakeStrictRedis()
STREAM = 'emails'
GROUP  = 'mailers'
DLQ_STREAM = 'emails:dlq'
DLQ_GROUP = 'mailers_dlq'
try:
    r.xgroup_create(STREAM, GROUP, id='0', mkstream=True)
except Exception as e:
    print('group exists:', e)
try:
    r.xgroup_create(DLQ_STREAM, DLQ_GROUP, id='0', mkstream=True)
except Exception as e:
    print('dlq group exists:', e)

def enqueue_email(to, subject, body, retries=0):
    job_id = uuid.uuid4().hex[:8]
    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': subject, 'body': body, 'retries': retries})
    r.set(f'jobresult:{job_id}', 'queued')
    return job_id

print('queue ready; DLQ streams defined.')

# Re-execute 8SxQA8uoVa0e to ensure worker is setup with DLQ_STREAM
import threading, time

def run_worker(max_msgs=10):
    processed = 0
    resp = r.xreadgroup(GROUP, 'worker-1', {STREAM: '>'}, count=max_msgs, block=0)
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            job_id = f['job_id']
            to = f['to']
            retries = int(f.get('retries', 0))

            if 'fail' in to:
                print(f"[Worker] Simulating failure for job {job_id} (to: {to})")
                if retries < 2:
                    print(f"[Worker] Retrying job {job_id}. Retries: {retries+1}")
                    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': f['subject'], 'body': f['body'], 'retries': retries + 1})
                    r.set(f"jobresult:{job_id}", f"retrying {retries+1}")
                else:
                    print(f"[Worker] Moving job {job_id} to DLQ (max retries reached)")
                    r.xadd(DLQ_STREAM, {'job_id': job_id, 'to': to, 'subject': f['subject'], 'body': f['body'], 'status': 'failed'})
                    r.set(f"jobresult:{job_id}", 'failed_dlq')
            else:
                print(f"[Worker] Sending email for job {job_id} to {to}")
                r.set(f"jobresult:{job_id}", 'sent')

            r.xack(STREAM, GROUP, msg_id)
            processed += 1
    return processed

def inspect_dlq():
    dlq_messages = []
    resp = r.xread({DLQ_STREAM: '0-0'}, count=100, block=0)
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            dlq_messages.append({'msg_id': msg_id.decode(), **f})
    return dlq_messages

worker_running = True
def worker_loop():
    while worker_running:
        processed_msgs = run_worker()
        if processed_msgs > 0:
            print(f"[Background Worker] Processed {processed_msgs} message(s).")
        time.sleep(0.1)

# Ensure only one worker thread is started if this cell is re-executed
if not any(t.name == 'WorkerThread' for t in threading.enumerate()):
    worker_thread = threading.Thread(target=worker_loop, daemon=True, name='WorkerThread')
    worker_thread.start()
    print('Background worker thread started.')
else:
    print('Background worker thread already running.')

# Re-execute ctMTehqUVjxc for basic tool functions
def check_inventory(sku: str):
    row = db.execute('SELECT sku,name,qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not row:
        return {'error': f'unknown sku {sku}'}
    return {'sku': row[0], 'name': row[1], 'qty': row[2], 'price': row[3]}

def send_confirmation(to: str, order_id: int):
    job_id = enqueue_email(to, f'Order {order_id} confirmed', f'Your order {order_id} is on its way.')
    return {'job_id': job_id, 'status': 'queued'}

def check_job(job_id: str):
    v = r.get(f'jobresult:{job_id}')
    return {'job_id': job_id, 'status': v.decode() if v else 'unknown'}

print('Basic tool functions defined.')

# Re-execute 2856577c for verify_order
def verify_order(order_id: int):
    row = db.execute('SELECT id, sku, qty, total, status FROM orders WHERE id=? LIMIT 1', (order_id,)).fetchone()
    if not row:
        return {'error': f'Order {order_id} not found'}
    order_details = {'id': row[0], 'sku': row[1], 'qty': row[2], 'total': row[3], 'status': row[4]}
    is_verified = order_details['status'] in ['created', 'sent']
    return {'order_id': order_id, 'verified': is_verified, 'details': order_details}

print('verify_order function defined.')

# Re-execute 8f934f9a for approve_order and modified create_order
APPROVAL_THRESHOLD = 500.0

def approve_order(order_id: int):
    row = db.execute('SELECT status FROM orders WHERE id=? LIMIT 1', (order_id,)).fetchone()
    if not row:
        return {'error': f'Order {order_id} not found'}
    if row[0] != 'needs_approval':
        return {'error': f'Order {order_id} does not need approval (current status: {row[0]})'}

    db.execute('UPDATE orders SET status=? WHERE id=?', ('created', order_id))
    db.commit()
    return {'order_id': order_id, 'status': 'approved'}

def create_order(sku: str, qty: int):
    cur = db.execute('SELECT qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not cur:
        return {'error': f'unknown sku {sku}'}
    have, price = cur
    if qty <= 0:
        return {'error': 'qty must be positive'}
    if have < qty:
        return {'error': f'insufficient stock: have {have}, need {qty}'}

    total = round(price * qty, 2)
    status = 'created'
    if total > APPROVAL_THRESHOLD:
        status = 'needs_approval'

    db.execute('UPDATE inventory SET qty=qty-? WHERE sku=?', (qty, sku))
    cur2 = db.execute('INSERT INTO orders (sku,qty,total,status) VALUES (?,?,?,?)',
                      (sku, qty, total, status))
    db.commit()
    return {'order_id': cur2.lastrowid, 'sku': sku, 'qty': qty, 'total': total, 'status': status}

print('approve_order and modified create_order functions defined.')

# Re-execute KlqZf8XsV2vV to define run_tool, print_trace_table, and setup TOOLS/DISPATCH
import time

TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':'Create an order for a SKU and quantity. Fails if stock is insufficient.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
  {'name':'inspect_dlq','description':'Inspect the dead-letter queue for failed email jobs.',
   'input_schema':{'type':'object','properties':{}}},
  {'name': 'verify_order','description': 'Verify the details and status of a created order.',
   'input_schema': {'type': 'object', 'properties': {'order_id': {'type': 'integer'}}, 'required': ['order_id']}},
  {'name': 'approve_order', 'description': 'Approve an order that requires human intervention before fulfillment.',
   'input_schema': {'type': 'object', 'properties': {'order_id': {'type': 'integer'}}, 'required': ['order_id']}}
]
DISPATCH = {'check_inventory':check_inventory,'create_order':create_order,
            'send_confirmation':send_confirmation,'check_job':check_job,
            'inspect_dlq':inspect_dlq, 'verify_order':verify_order, 'approve_order':approve_order}

trace_spans = []

def run_tool(name, args):
    start_time = time.perf_counter()
    fn = DISPATCH.get(name)
    if not fn:
        end_time = time.perf_counter()
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': False, 'error': f'unknown tool {name}'})
        return {'error': f'unknown tool {name}'}, True
    try:
        out = fn(**args)
        end_time = time.perf_counter()
        is_err = isinstance(out, dict) and 'error' in out
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': not is_err, 'result': out})
        return out, is_err
    except Exception as e:
        end_time = time.perf_counter()
        trace_spans.append({'tool': name, 'args': args, 'ms': (end_time - start_time) * 1000, 'ok': False, 'error': repr(e)})
        return {'error': repr(e)}, True

def print_trace_table():
    global trace_spans
    if not trace_spans:
        print('No tool calls made in this turn.')
        return

    print('\n--- Tool Call Trace ---')
    print(f"| {'Tool':<20} | {'Args':<40} | {'MS':>8} | {'OK':<5} |")
    print(f"| {'-'*20} | {'-'*40} | {'-'*8} | {'-'*5} |")
    for span in trace_spans:
        tool_name = span['tool']
        args_str = str(span['args'])
        if len(args_str) > 40: args_str = args_str[:37] + '...'
        ms = f"{span['ms']:.2f}"
        ok = '✅' if span['ok'] else '❌'
        print(f"| {tool_name:<20} | {args_str:<40} | {ms:>8} | {ok:<5} |")
    print('-----------------------')
    trace_spans = []

print('run_tool and print_trace_table defined, TOOLS/DISPATCH updated.')

# Re-execute 6e6afb52 to set final SYSTEM prompt
SYSTEM = (
  'You are an ordering agent. To place an order: first check_inventory, then create_order. ' \
  'If an order needs approval, use the `approve_order` tool. Then, send_confirmation with the returned order_id. ' \
  'After these steps, **you must use the `verify_order` tool to confirm the order details and status** before reporting success. ' \
  'Report the order total, the order status, and the email job status. ' \
  'If stock is insufficient, say so and do not create the order.'
)

print('Final SYSTEM prompt updated.')

# Re-execute fiEMUZFOV9MZ for agent function with tracing
from anthropic import Anthropic
def agent(user_text, max_steps=8, verbose=True):
    global trace_spans
    trace_spans = []

    if not LIVE:
        if verbose: print('… (mock) chaining check_inventory → create_order → send_confirmation')
        inv,_ = run_tool('check_inventory', {'sku':'MON-4'})
        od,_  = run_tool('create_order', {'sku':'MON-4','qty':1})
        jb,_  = run_tool('send_confirmation', {'to':'asha@x.com','order_id':od['order_id']})
        st,_  = run_tool('check_job', {'job_id':jb['job_id']})
        print_trace_table()
        return f"(mock) Order {od['order_id']} total ${od['total']}; email {st['status']}."

    A = Anthropic()
    messages = [{'role':'user','content':user_text}]
    for _ in range(max_steps):
        resp = A.messages.create(model=MODEL, max_tokens=1024, system=SYSTEM, tools=TOOLS, messages=messages)
        if resp.stop_reason == 'tool_use':
            messages.append({'role':'assistant','content':[b.model_dump() for b in resp.content]})
            results = []
            for b in resp.content:
                if b.type == 'tool_use':
                    if verbose: print(f'  → {b.name}({b.input})')
                    out, is_err = run_tool(b.name, b.input)
                    results.append({'type':'tool_result','tool_use_id':b.id,
                                    'content':json.dumps(out),'is_error':is_err})
            messages.append({'role':'user','content':results})
            continue

        final_response = ''.join(b.text for b in resp.content if b.type=='text')
        print_trace_table()
        return final_response

    print_trace_table()
    return '(max steps reached)'

print('Agent function with tracing defined.')

# --- Rerunning demonstrations ---

# Re-check inventory as some orders were placed before
print('\n--- Re-checking inventory initial state ---\n')
db.execute('DROP TABLE IF EXISTS inventory')
db.execute('DROP TABLE IF EXISTS orders')
db.execute('CREATE TABLE inventory (sku TEXT PRIMARY KEY, name TEXT, qty INTEGER, price REAL)')
db.execute('CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT, qty INTEGER, total REAL, status TEXT)')
db.executemany('INSERT INTO inventory VALUES (?,?,?,?)', [
    ('KB-01', 'Mechanical keyboard', 12, 129.0),
    ('HUB-2', 'USB-C hub',           0,  58.0),
    ('MON-4', '4K monitor',          5, 410.0),
])
db.commit()
print('Inventory and orders tables reset.')

# Clear Redis for a clean demonstration
r.flushall()
print('Redis flushed.')

# Rerun DLQ demonstration
print('\n--- Rerunning DLQ demonstration ---\n')
print("Attempting to send an email to 'fail_recipient@x.com' to demonstrate DLQ:")
dlq_job = send_confirmation('fail_recipient@x.com', 99) # Using a dummy order_id as actual order not placed yet
print(f"Initial status for DLQ job {dlq_job['job_id']}: {check_job(dlq_job['job_id'])['status']}")

print("Waiting for background worker to process... (3 seconds)")
time.sleep(3)

print(f"Status after 1st retry: {check_job(dlq_job['job_id'])['status']}")
time.sleep(1)
print(f"Status after 2nd retry: {check_job(dlq_job['job_id'])['status']}")
time.sleep(1)
print(f"Final status (should be in DLQ): {check_job(dlq_job['job_id'])['status']}")

print("\nInspecting Dead-Letter Queue:")
print(inspect_dlq())

# Rerun Human-in-the-loop demonstration
print('\n--- Rerunning Human-in-the-loop demonstration ---\n')
# Order below threshold (should proceed normally)
print(agent('Order one USB-C hub (SKU HUB-2) and email user@example.com.'))
print("\n----------------------------------\n")
# Order above threshold (should trigger approval flow)
print(agent('Order three 4K monitors (SKU MON-4) and email manager@example.com.'))
print("\n----------------------------------\n")
# Re-check inventory for MON-4
print(check_inventory('MON-4'))

