# -*- coding: utf-8 -*-
"""Day_17_Hume.ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_LcC3JXj4lmHcZHG4gr-7oUu5W04rgLE
"""

!pip install yt-dlp hume



from google.colab import userdata
HUME_KEY=userdata.get('hume_key')

!pip install --upgrade hume

import hume

print(hume.__version__)

from hume import HumeClient

client = HumeClient(api_key="HUME_KEY")

result = client.expression_measurement.batch.predict(
    texts=["I am very happy today"]
)

print(result)

from hume.client import HumeClient

client = HumeClient(api_key="YOUR_API_KEY")
print(client)

from hume.client import HumeClient

client = HumeClient(api_key="HUME_KEY")

print(dir(client))

from hume.client import HumeClient

client = HumeClient(api_key="YOUR_API_KEY")

print(dir(client.empathic_voice))

from hume import HumeClient
from hume.models.config import LanguageConfig

client = HumeClient(api_key=HUME_KEY)

language_config = LanguageConfig()

result = client.predict(
    text=["I am very happy today"],
    configs=[language_config]
)

print(result)

from hume.client import HumeClient

client = HumeClient(api_key="YOUR_API_KEY")

print(dir(client.empathic_voice))

print(dir(client.empathic_voice.chat))
