# -*- coding: utf-8 -*-
"""Supervisor_Researcher_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LpTbPoy5kMUrRvJZZCPDMTnVoBpUlmTx
"""

import operator
from typing import Annotated, List, TypedDict, Literal
from pydantic import BaseModel, Field

# The State object that travels through the graph
class AgentState(TypedDict):
    task: str
    research_notes: Annotated[List[str], operator.add]
    draft: str
    next_node: str
    retry_count: int
    revision_feedback: str

# Schema for the Supervisor to follow
class Router(BaseModel):
    """Decide which worker to call next."""
    next_worker: Literal["researcher", "writer", "FINISH"] = Field(description="The next node to act")
    instructions: str = Field(description="Specific instructions for the worker")
    is_critical: bool = Field(description="If True, system will pause for human review")



from google.colab import userdata
TAVILY_KEY=userdata.get('tavily_apikey')
GROQ_API_KEY=userdata.get('grok_api_key')

import sys
!{sys.executable} -m pip install -q langchain-groq langchain-community langchain-tavily

import os

from langchain_groq import ChatGroq
from langchain_tavily import TavilySearch # Updated import

# Using Llama 3.3 70B for the "Brain" (Supervisor)
llm = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0, groq_api_key=GROQ_API_KEY)
search_tool = TavilySearch(k=2, tavily_api_key=TAVILY_KEY) # Updated class name and passing key directly

def researcher(state: AgentState):
    print("🚀 Researcher is digging...")
    query = state['task']
    results = search_tool.invoke(query)
    print(results)
    return {"research_notes": [str(results)], "retry_count": 0}

def writer(state: AgentState):
    print("✍️ Writer is composing...")
    context = "\n".join(state['research_notes'])
    res = llm.invoke(f"Write a report on {state['task']} using: {context}")
    return {"draft": res.content}

def supervisor(state: AgentState):
    print("🧠 Supervisor is reviewing state...")
    # Groq supports structured output natively
    structured_llm = llm.with_structured_output(Router)

    prompt = f"""
    Task: {state['task']}
    Notes collected: {len(state['research_notes'])}
    Current Draft: {state['draft'][:100]}...
    If you have something in research_notes, select writer
    """
    print(f"Supervisor sees {len(state['research_notes'])} notes and draft length {len(state['draft'])}")
    decision = structured_llm.invoke(prompt)
    return {
        "next_node": decision.next_worker,
        "revision_feedback": decision.instructions
    }

# Graph with recovery and breakpoints
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

builder = StateGraph(AgentState)

# Add nodes
builder.add_node("supervisor", supervisor)
builder.add_node("researcher", researcher)
builder.add_node("writer", writer)

# Logic
builder.set_entry_point("supervisor")

builder.add_conditional_edges(
    "supervisor",
    lambda x: x["next_node"],
    {"researcher": "researcher", "writer": "writer", "FINISH": END}
)

builder.add_edge("researcher", "supervisor")
builder.add_edge("writer", "supervisor")

# Enable Persistence (Recovery) and Breakpoints (Pause)
memory = MemorySaver()
graph = builder.compile(
    checkpointer=memory,
    interrupt_before=["writer"] # PAUSE: Allows human to review research before writing starts
)

config = {"configurable": {"thread_id": "workshop_user_1"}}
initial_input = {"task": "Impact of LPU architecture on AI inference speeds", "research_notes": [], "retry_count": 0, "draft": ""}

# 1. Start execution
print("--- STARTING GRAPH ---")
for event in graph.stream(initial_input, config, stream_mode="values"):
    if "next_node" in event:
        print(f"Moving to: {event['next_node']}")

# 2. Check if we hit a breakpoint (Pause)
snapshot = graph.get_state(config)
if snapshot.next:
    print(f"\n⏸️ SYSTEM PAUSED. Next step is: {snapshot.next}")
    print(f"Feedback from Supervisor: {snapshot.values['revision_feedback']}")

    # 3. Resume (Human says 'Go ahead')
    print("\n--- RESUMING AFTER PAUSE ---")
    #for event in graph.stream(None, config, stream_mode="values"):
    #    print("Finalizing...")

print("--- RESUMING GRAPH ---\n")
for event in graph.stream(None, config, stream_mode="values"):
    if "next_node" in event:
        print(f"Moving to: {event['next_node']}")
    elif "draft" in event:
        print(f"\n--- FINAL DRAFT ---:\n{event['draft']}")

from IPython.display import Image, display
display(Image(graph.get_graph().draw_mermaid_png()))

import sys
!{sys.executable} -m pip install -q streamlit

"""Next, I'll create the `app.py` file which will contain the Streamlit application logic and your LangGraph agent definitions. This ensures the Streamlit app can run independently."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import os
# import operator
# from typing import Annotated, List, TypedDict, Literal
# from pydantic import BaseModel, Field
# from google.colab import userdata
# 
# from langchain_groq import ChatGroq
# from langchain_tavily import TavilySearch
# from langgraph.graph import StateGraph, END
# from langgraph.checkpoint.memory import MemorySaver
# 
# # --- Agent State and Router Definitions ---
# 
# class AgentState(TypedDict):
#     task: str
#     research_notes: Annotated[List[str], operator.add]
#     draft: str
#     next_node: str
#     retry_count: int
#     revision_feedback: str
# 
# class Router(BaseModel):
#     """Decide which worker to call next."""
#     next_worker: Literal["researcher", "writer", "FINISH"] = Field(description="The next node to act")
#     instructions: str = Field(description="Specific instructions for the worker")
#     is_critical: bool = Field(description="If True, system will pause for human review")
# 
# # --- API Key Setup ---
# TAVILY_KEY = userdata.get('tavily_apikey')
# GROQ_API_KEY = userdata.get('grok_api_key')
# os.environ["GROQ_API_KEY"] = GROQ_API_KEY # Ensure it's set for ChatGroq
# os.environ["TAVILY_API_KEY"] = TAVILY_KEY # Ensure it's set for TavilySearch (though we pass directly)
# 
# # --- LLM and Tool Initialization ---
# llm = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0, groq_api_key=GROQ_API_KEY)
# search_tool = TavilySearch(k=2, tavily_api_key=TAVILY_KEY)
# 
# # --- Agent Functions ---
# def researcher(state: AgentState):
#     st.info("🚀 Researcher is digging...")
#     query = state['task']
#     results = search_tool.invoke(query)
#     st.write("Research Results:", results)
#     return {"research_notes": [str(results)], "retry_count": 0}
# 
# def writer(state: AgentState):
#     st.info("✍️ Writer is composing...")
#     context = "\n".join(state['research_notes'])
#     res = llm.invoke(f"Write a report on {state['task']} using: {context}")
#     return {"draft": res.content}
# 
# def supervisor(state: AgentState):
#     st.info("🧠 Supervisor is reviewing state...")
#     structured_llm = llm.with_structured_output(Router)
# 
#     prompt = f"""
#     Task: {state['task']}
#     Notes collected: {len(state['research_notes'])}
#     Current Draft: {state['draft'][:100]}...
#     Given the current state and task, decide the next action.
#     If research_notes are empty, go to researcher.
#     If research_notes are available and no draft, go to writer.
#     If draft is available, FINISH.
#     """
#     st.write(f"Supervisor sees {len(state['research_notes'])} notes and draft length {len(state['draft'])}")
#     decision = structured_llm.invoke(prompt)
#     st.write(f"Supervisor Decision: Next worker is {decision.next_worker} with instructions: {decision.instructions}")
#     return {
#         "next_node": decision.next_worker,
#         "revision_feedback": decision.instructions
#     }
# 
# # --- LangGraph Setup ---
# builder = StateGraph(AgentState)
# builder.add_node("supervisor", supervisor)
# builder.add_node("researcher", researcher)
# builder.add_node("writer", writer)
# builder.set_entry_point("supervisor")
# 
# builder.add_conditional_edges(
#     "supervisor",
#     lambda x: x["next_node"],
#     {"researcher": "researcher", "writer": "writer", "FINISH": END}
# )
# 
# builder.add_edge("researcher", "supervisor")
# builder.add_edge("writer", "supervisor")
# 
# memory = MemorySaver()
# graph = builder.compile(checkpointer=memory)
# 
# # --- Streamlit UI ---
# st.set_page_config(page_title="LangGraph Agent Demo", layout="wide")
# st.title("LangGraph Agent Demo")
# 
# config = {"configurable": {"thread_id": "streamlit_user_1"}}
# 
# user_task = st.text_input("Enter your task for the AI agent:", "Impact of LPU architecture on AI inference speeds")
# 
# if st.button("Run Agent"):
#     initial_input = {"task": user_task, "research_notes": [], "retry_count": 0, "draft": "", "revision_feedback": ""}
# 
#     st.subheader("Agent Execution Log:")
#     full_draft = ""
# 
#     # Clear previous state in session for a fresh run
#     if 'graph_state' in st.session_state:
#         del st.session_state['graph_state']
# 
#     with st.spinner("Running the agent..."):
#         for step, event in enumerate(graph.stream(initial_input, config, stream_mode="values")):
#             st.write(f"--- Step {step + 1} ---")
#             if "next_node" in event:
#                 st.write(f"Moving to: {event['next_node']}")
#             if "research_notes" in event and event["research_notes"]:
#                 st.write(f"Collected {len(event['research_notes'])} research notes.")
#             if "draft" in event and event["draft"]:
#                 full_draft = event["draft"]
#                 st.write("Draft in progress...")
#             st.json(event) # Display full event for debugging
# 
#             # Simple breakpoint simulation: If the supervisor recommends pausing for human review,
#             # we can output the feedback. For a true interactive pause, more Streamlit state management is needed.
#             if "revision_feedback" in event and event["revision_feedback"] and event["next_node"] != "FINISH":
#                  st.warning(f"Agent suggests human review: {event['revision_feedback']}")
# 
#     if full_draft:
#         st.subheader("Final Draft:")
#         st.markdown(full_draft)
#     else:
#         st.info("Agent finished without producing a final draft for this run.")
#

"""Now, run the Streamlit application. This will generate a public URL that you can click to access your app. This process can take a few minutes to start up."""

!streamlit run app.py & npx localtunnel --port 8501

!streamlit run app.py & npx localtunnel --port 8501

